### ISSUE TITLE
Misinterpreted na.rm = TRUE argument when translated into SQL conditional function, if()

### ISSUE THREAD

**Issue by krprasangdas** [tidyverse/dbplyr#1320]
Below is an example which demonstrates the use of na.rm = TRUE argument for pmin() function.
The arguments are translated incorrectly into SQL and the condition appear as "arg1 <= arg2 and ... and **argN-1 <= TRUE**".
Similar is the case with pmax() function.
The obvious workaround at this point is to substitute NA as something to get these functions work.

``` r
library(sparklyr)
#> 
#> Attaching package: 'sparklyr'
#> The following object is masked from 'package:stats':
#> 
#>     filter
library(dbplyr)
library(arrow)
#> 
#> Attaching package: 'arrow'
#> The following object is masked from 'package:utils':
#> 
#>     timestamp
library(ggplot2)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:dbplyr':
#> 
#>     ident, sql
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

spark_disconnect_all()
#> [1] 0
sc <- spark_connect("local")

mpgs <- mpg %>% copy_to(sc, ., "mpg", ovewrite = TRUE)

mpgs_r <- mpgs %>% 
  mutate(
    myvar = pmin(
      case_when(cty > hwy ~ hwy, TRUE ~ as.integer(NA)),
      case_when(displ * 10 > hwy ~ hwy, TRUE ~ as.integer(NA)),
      na.rm = TRUE
    )
  )

mpgs_r %>% show_query
#> <SQL>
#> SELECT
#>   *,
#>   if(CASE WHEN (`cty` > `hwy`) THEN `hwy` ELSE (CAST(NULL AS INT)) END <= CASE WHEN ((`displ` * 10.0) > `hwy`) THEN `hwy` ELSE (CAST(NULL AS INT)) END and CASE WHEN (`cty` > `hwy`) THEN `hwy` ELSE (CAST(NULL AS INT)) END <= TRUE, CASE WHEN (`cty` > `hwy`) THEN `hwy` ELSE (CAST(NULL AS INT)) END, if(CASE WHEN ((`displ` * 10.0) > `hwy`) THEN `hwy` ELSE (CAST(NULL AS INT)) END <= TRUE, CASE WHEN ((`displ` * 10.0) > `hwy`) THEN `hwy` ELSE (CAST(NULL AS INT)) END, TRUE)) AS `myvar`
#> FROM `mpg`

mpgs_r
#> Error: org.apache.spark.sql.AnalysisException: cannot resolve '(CASE WHEN (mpg.`cty` > mpg.`hwy`) THEN mpg.`hwy` ELSE CAST(NULL AS INT) END <= true)' due to data type mismatch: differing types in '(CASE WHEN (mpg.`cty` > mpg.`hwy`) THEN mpg.`hwy` ELSE CAST(NULL AS INT) END <= true)' (int and boolean).; line 3 pos 155;
#> 'Project [manufacturer#68, model#69, displ#70, year#71, cyl#72, trans#73, drv#74, cty#75, hwy#76, fl#77, class#78, 'if(((CASE WHEN (cty#75 > hwy#76) THEN hwy#76 ELSE cast(null as int) END <= CASE WHEN ((displ#70 * cast(10.0 as double)) > cast(hwy#76 as double)) THEN hwy#76 ELSE cast(null as int) END) && (CASE WHEN (cty#75 > hwy#76) THEN hwy#76 ELSE cast(null as int) END <= true)), CASE WHEN (cty#75 > hwy#76) THEN hwy#76 ELSE cast(null as int) END, 'if((CASE WHEN ((displ#70 * cast(10.0 as double)) > cast(hwy#76 as double)) THEN hwy#76 ELSE cast(null as int) END <= true), CASE WHEN ((displ#70 * cast(10.0 as double)) > cast(hwy#76 as double)) THEN hwy#76 ELSE cast(null as int) END, true)) AS myvar#254]
#> +- SubqueryAlias `mpg`
#>    +- LogicalRDD [manufacturer#68, model#69, displ#70, year#71, cyl#72, trans#73, drv#74, cty#75, hwy#76, fl#77, class#78], false
#> 
#>  at org.apache.spark.sql.catalyst.analysis.package$AnalysisErrorAt.failAnalysis(package.scala:42)
#>  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1$$anonfun$apply$3.applyOrElse(CheckAnalysis.scala:119)
#>  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1$$anonfun$apply$3.applyOrElse(CheckAnalysis.scala:111)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$1.apply(TreeNode.scala:280)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$1.apply(TreeNode.scala:280)
#>  at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:69)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:279)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:277)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:277)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:328)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:186)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:326)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:277)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:277)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:277)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode.org$apache$spark$sql$catalyst$trees$TreeNode$$mapChild$2(TreeNode.scala:297)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4$$anonfun$apply$13.apply(TreeNode.scala:356)
#>  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
#>  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
#>  at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
#>  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
#>  at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
#>  at scala.collection.AbstractTraversable.map(Traversable.scala:104)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:356)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:186)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:326)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:277)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:277)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:277)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:328)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:186)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:326)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:277)
#>  at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$transformExpressionsUp$1.apply(QueryPlan.scala:93)
#>  at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$transformExpressionsUp$1.apply(QueryPlan.scala:93)
#>  at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$1.apply(QueryPlan.scala:105)
#>  at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$1.apply(QueryPlan.scala:105)
#>  at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:69)
#>  at org.apache.spark.sql.catalyst.plans.QueryPlan.transformExpression$1(QueryPlan.scala:104)
#>  at org.apache.spark.sql.catalyst.plans.QueryPlan.org$apache$spark$sql$catalyst$plans$QueryPlan$$recursiveTransform$1(QueryPlan.scala:116)
#>  at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$org$apache$spark$sql$catalyst$plans$QueryPlan$$recursiveTransform$1$2.apply(QueryPlan.scala:121)
#>  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
#>  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
#>  at scala.collection.immutable.List.foreach(List.scala:392)
#>  at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
#>  at scala.collection.immutable.List.map(List.scala:296)
#>  at org.apache.spark.sql.catalyst.plans.QueryPlan.org$apache$spark$sql$catalyst$plans$QueryPlan$$recursiveTransform$1(QueryPlan.scala:121)
#>  at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$2.apply(QueryPlan.scala:126)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:186)
#>  at org.apache.spark.sql.catalyst.plans.QueryPlan.mapExpressions(QueryPlan.scala:126)
#>  at org.apache.spark.sql.catalyst.plans.QueryPlan.transformExpressionsUp(QueryPlan.scala:93)
#>  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1.apply(CheckAnalysis.scala:111)
#>  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1.apply(CheckAnalysis.scala:89)
#>  at org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:126)
#>  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$class.checkAnalysis(CheckAnalysis.scala:89)
#>  at org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis(Analyzer.scala:95)
#>  at org.apache.spark.sql.catalyst.analysis.Analyzer$$anonfun$executeAndCheck$1.apply(Analyzer.scala:108)
#>  at org.apache.spark.sql.catalyst.analysis.Analyzer$$anonfun$executeAndCheck$1.apply(Analyzer.scala:105)
#>  at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.markInAnalyzer(AnalysisHelper.scala:201)
#>  at org.apache.spark.sql.catalyst.analysis.Analyzer.executeAndCheck(Analyzer.scala:105)
#>  at org.apache.spark.sql.execution.QueryExecution.analyzed$lzycompute(QueryExecution.scala:58)
#>  at org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:56)
#>  at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:48)
#>  at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:78)
#>  at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:643)
#>  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#>  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
#>  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
#>  at java.lang.reflect.Method.invoke(Method.java:498)
#>  at sparklyr.Invoke.invoke(invoke.scala:161)
#>  at sparklyr.StreamHandler.handleMethodCall(stream.scala:141)
#>  at sparklyr.StreamHandler.read(stream.scala:62)
#>  at sparklyr.BackendHandler$$anonfun$channelRead0$1.apply$mcV$sp(handler.scala:60)
#>  at scala.util.control.Breaks.breakable(Breaks.scala:38)
#>  at sparklyr.BackendHandler.channelRead0(handler.scala:40)
#>  at sparklyr.BackendHandler.channelRead0(handler.scala:14)
#>  at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
#>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
#>  at io.netty.channel.AbstractChan
```

<sup>Created on 2023-06-30 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.0.2 (2020-06-22)
#>  os       Red Hat Enterprise Linux
#>  system   x86_64, linux-gnu
#>  ui       X11
#>  language (EN)
#>  collate  en_US.UTF-8
#>  ctype    en_US.UTF-8
#>  tz       America/Chicago
#>  date     2023-06-30
#>  pandoc   2.19.2 @ /opt/revr/rstudio-server/bin/quarto/bin/tools/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version  date (UTC) lib source
#>  arrow       * 11.0.0.3 2023-03-08 [2] RSPM (R 4.0.2)
#>  askpass       1.1      2019-01-13 [2] RSPM (R 4.0.2)
#>  assertthat    0.2.1    2019-03-21 [2] RSPM (R 4.0.2)
#>  base64enc     0.1-3    2015-07-28 [2] RSPM (R 4.0.2)
#>  bit           4.0.5    2022-11-15 [2] RSPM (R 4.0.2)
#>  bit64         4.0.5    2020-08-30 [2] RSPM (R 4.0.2)
#>  blob          1.2.4    2023-03-17 [2] RSPM (R 4.0.2)
#>  cli           3.6.1    2023-03-23 [2] RSPM (R 4.0.2)
#>  colorspace    2.1-0    2023-01-23 [2] RSPM (R 4.0.2)
#>  config        0.3.1    2020-12-17 [2] RSPM (R 4.0.2)
#>  DBI           1.1.3    2022-06-18 [2] RSPM (R 4.0.2)
#>  dbplyr      * 2.3.2    2023-03-21 [2] RSPM (R 4.0.2)
#>  digest        0.6.31   2022-12-11 [2] RSPM (R 4.0.2)
#>  dplyr       * 1.1.1    2023-03-22 [2] RSPM (R 4.0.2)
#>  ellipsis      0.3.2    2021-04-29 [2] RSPM (R 4.0.2)
#>  evaluate      0.20     2023-01-17 [2] RSPM (R 4.0.2)
#>  fansi         1.0.4    2023-01-22 [2] RSPM (R 4.0.2)
#>  fastmap       1.1.1    2023-02-24 [2] RSPM (R 4.0.2)
#>  forge         0.2.0    2019-02-26 [2] RSPM (R 4.0.2)
#>  fs            1.6.1    2023-02-06 [2] RSPM (R 4.0.2)
#>  generics      0.1.3    2022-07-05 [2] RSPM (R 4.0.2)
#>  ggplot2     * 3.4.2    2023-04-03 [2] RSPM (R 4.0.2)
#>  glue          1.6.2    2022-02-24 [2] RSPM (R 4.0.2)
#>  gtable        0.3.3    2023-03-21 [2] RSPM (R 4.0.2)
#>  htmltools     0.5.5    2023-03-23 [2] RSPM (R 4.0.2)
#>  htmlwidgets   1.6.2    2023-03-17 [2] RSPM (R 4.0.2)
#>  httr          1.4.5    2023-02-24 [2] RSPM (R 4.0.2)
#>  jsonlite      1.8.4    2022-12-06 [2] RSPM (R 4.0.2)
#>  knitr         1.42     2023-01-25 [2] RSPM (R 4.0.2)
#>  lifecycle     1.0.3    2022-10-07 [2] RSPM (R 4.0.2)
#>  magrittr      2.0.3    2022-03-30 [2] RSPM (R 4.0.2)
#>  munsell       0.5.0    2018-06-12 [2] RSPM (R 4.0.2)
#>  openssl       2.0.6    2023-03-09 [2] RSPM (R 4.0.2)
#>  pillar        1.9.0    2023-03-22 [2] RSPM (R 4.0.2)
#>  pkgconfig     2.0.3    2019-09-22 [2] RSPM (R 4.0.2)
#>  purrr         1.0.1    2023-01-10 [2] RSPM (R 4.0.2)
#>  R.cache       0.16.0   2022-07-21 [2] RSPM (R 4.0.2)
#>  R.methodsS3   1.8.2    2022-06-13 [2] RSPM (R 4.0.2)
#>  R.oo          1.25.0   2022-06-12 [2] RSPM (R 4.0.2)
#>  R.utils       2.12.2   2022-11-11 [2] RSPM (R 4.0.2)
#>  r2d3          0.2.6    2022-02-28 [2] RSPM (R 4.0.2)
#>  R6            2.5.1    2021-08-19 [2] RSPM (R 4.0.2)
#>  reprex        2.0.2    2022-08-17 [2] RSPM (R 4.0.2)
#>  rlang         1.1.0    2023-03-14 [2] RSPM (R 4.0.2)
#>  rmarkdown     2.21     2023-03-26 [2] RSPM (R 4.0.2)
#>  rprojroot     2.0.3    2022-04-02 [2] RSPM (R 4.0.2)
#>  rstudioapi    0.14     2022-08-22 [2] RSPM (R 4.0.2)
#>  scales        1.2.1    2022-08-20 [2] RSPM (R 4.0.2)
#>  sessioninfo   1.2.2    2021-12-06 [2] RSPM (R 4.0.2)
#>  sparklyr    * 1.8.1    2023-03-22 [2] RSPM (R 4.0.2)
#>  styler        1.9.1    2023-03-04 [2] RSPM (R 4.0.2)
#>  tibble        3.2.1    2023-03-20 [2] RSPM (R 4.0.2)
#>  tidyr         1.3.0    2023-01-24 [2] RSPM (R 4.0.2)
#>  tidyselect    1.2.0    2022-10-10 [2] RSPM (R 4.0.2)
#>  utf8          1.2.3    2023-01-31 [2] RSPM (R 4.0.2)
#>  vctrs         0.6.1    2023-03-22 [2] RSPM (R 4.0.2)
#>  withr         2.5.0    2022-03-03 [2] RSPM (R 4.0.2)
#>  xfun          0.38     2023-03-24 [2] RSPM (R 4.0.2)
#>  yaml          2.3.7    2023-01-23 [2] RSPM (R 4.0.2)
#> 
#>  [1] /shared/nas/shape/bu_dsaid/transient/pkumard/R/x86_64-pc-linux-gnu-library/3.5
#>  [2] /opt/revr/library/4.0/2023-04-17/cran
#>  [3] /opt/revr/library/4.0/2023-04-17/bio
#>  [4] /opt/revr/library/4.0/2023-04-17/github
#>  [5] /opt/revr/library/4.0/2023-04-17/misc
#>  [6] /opt/revr/library/4.0/2023-04-17/tu
#>  [7] /opt/revr/ropen/4.0.2/lib64/R/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

**Comment by mgirlich** [comment]
Thanks for opening the issue.
It would be great if you could try to make your reprex a bit smaller. That is, remove unnecessary code (e.g. `library(arrow)`). Also, if the issue is with `pmin()` maybe something simpler than `case_when()` works or you only need one of the `case_when()`. This really helps a lot in diagnosing such issues. Thanks 😄 
This seems to be a sparklyr issue, not a dbplyr one. So can you please open an issue in the [sparklyr repository](https://github.com/sparklyr/sparklyr/issues) instead?
